---
# tasks file for ansible-telegraf

- name: "Install the correct repository"
  include_tasks: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- name: "Install the correct repository"
  include_tasks: "Debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - telegraf
    - packages

- name: "Configure telegraf"
  include_tasks: "configure.yml"
