---
- hosts: all
  pre_tasks:
    - name: "Installing which on CentOS"
      yum:
        name: which
        state: present
      when:
        - ansible_os_family == 'RedHat'

    - name: "Installing wget on Debian"
      apt:
        name: "{{ item }}"
        state: present
      when:
        - ansible_os_family == 'Debian'
      with_items:
        - wget
        - gpg

  roles:
    - role: ansible-telegraf
